/*
* ORACLE
* JOIN, GROUP BY, 스칼라 서브쿼리
*/

SELECT T1.YEAR
        ,T1.MONTH
        , COUNT(DISTINCT USER_ID) PURCHASED_USERS
        , ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED BETWEEN TO_DATE('2021-01-01','YYYY-MM-DD') AND TO_DATE('2021-12-31','YYYY-MM-DD')), 1) PURCHASED_RATIO
FROM(
    SELECT TO_NUMBER(SUBSTR(TO_CHAR(SALES_DATE, 'YYYYMM'),1,4)) YEAR
            , TO_NUMBER(SUBSTR(TO_CHAR(SALES_DATE, 'YYYYMM'),5,2)) MONTH 
            , USER_INFO.USER_ID
    FROM ONLINE_SALE, USER_INFO
    WHERE 1=1
    AND ONLINE_SALE.USER_ID = USER_INFO.USER_ID
    AND JOINED BETWEEN TO_DATE('2021-01-01','YYYY-MM-DD') AND TO_DATE('2021-12-31','YYYY-MM-DD')
) T1
GROUP BY T1.YEAR, T1.MONTH
ORDER BY T1.YEAR, T1.MONTH