/*
* ORACLE
* 계층형 쿼리 + GROUP BY + DATETIME
*/
SELECT T1.HOUR, COALESCE(T2.CNT,0) COUNT
FROM(
    SELECT LEVEL-1 HOUR FROM DUAL CONNECT BY LEVEL<=24
) T1 ,(
    SELECT TO_NUMBER(SUBSTR(TO_CHAR(DATETIME,'YYYY-MM-DD HH24:MM:SS'),12,2)) HOUR, COUNT(*) CNT
    FROM ANIMAL_OUTS
    GROUP BY TO_NUMBER(SUBSTR(TO_CHAR(DATETIME,'YYYY-MM-DD HH24:MM:SS'),12,2))
    ORDER BY TO_NUMBER(SUBSTR(TO_CHAR(DATETIME,'YYYY-MM-DD HH24:MM:SS'),12,2))  
) T2
WHERE 1=1
AND T1.HOUR = T2.HOUR(+)
ORDER BY T1.HOUR